# Generated by Django 4.0.4 on 2022-06-30 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('District', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('Emergency_Phone', models.IntegerField()),
                ('Country', models.CharField(max_length=100)),
                ('Departure_Date', models.DateField(max_length=50)),
                ('Landing_Date', models.DateField(max_length=50)),
                ('Adult', models.CharField(max_length=50)),
                ('Children', models.CharField(max_length=50)),
                ('Departure_Airport', models.CharField(max_length=50)),
                ('Ticket_Type', models.CharField(max_length=50)),
                ('Landing_Airport', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='FlightCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=50)),
                ('Rate', models.FloatField()),
                ('Description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='FlightType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('One_Way', models.CharField(max_length=50)),
                ('Two_Way', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Category', models.CharField(max_length=50)),
                ('Rate', models.FloatField()),
                ('Description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('District', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('Emergency_Phone', models.IntegerField()),
                ('Country', models.CharField(max_length=100)),
                ('Arrive_Date', models.DateField(max_length=50)),
                ('Depart_Date', models.DateField(max_length=50)),
                ('Adult', models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five')], max_length=50)),
                ('Children', models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five')], max_length=50)),
                ('Destination_Hotel', models.CharField(choices=[('kathmandu', 'kathmandu'), ('bhaktapur', 'bhaktapur'), ('sanga', 'sanga'), ('banepa', 'banepa'), ('dhulikhel', 'dhulikhel'), ('panauti', 'panauti')], max_length=200)),
                ('Room_Type', models.CharField(choices=[('with bathroom', 'with bathroom'), ('without bathroom', 'without bathroom'), ('deluxe room', 'deluxe room'), ('super deluxe room', 'super deluxe room'), ('normal room', 'normal room')], max_length=100)),
                ('Choose_Hotel', models.CharField(choices=[('abc', 'abc'), ('bcd', 'bcd'), ('efg', 'efg'), ('ghi', 'ghi'), ('jkl', 'jkl')], max_length=100)),
                ('Bed_Type', models.CharField(choices=[('abc', 'abc'), ('bcd', 'bcd'), ('efg', 'efg'), ('ghi', 'ghi'), ('jkl', 'jkl')], max_length=100)),
                ('Description', models.TextField(max_length=2000)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.roomcat')),
            ],
        ),
        migrations.CreateModel(
            name='FlightBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Departure_Date', models.DateField()),
                ('Landing_Date', models.DateField()),
                ('Flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.flight')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.flightcat'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arrive_Date', models.DateField()),
                ('Depart_Date', models.DateField()),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.room')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
