# Generated by Django 4.0.4 on 2022-07-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=200)),
                ('Price', models.FloatField(max_length=50)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
