# Generated by Django 4.0.4 on 2022-07-18 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Category', models.CharField(max_length=50)),
                ('Rate', models.FloatField()),
                ('Description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.IntegerField()),
                ('District', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('Street', models.CharField(blank=True, max_length=100, null=True)),
                ('Emergency_Phone', models.IntegerField()),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Arrive_Date', models.DateField(blank=True, max_length=100, null=True)),
                ('Depart_Date', models.DateField(blank=True, max_length=100, null=True)),
                ('Adult', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100, null=True)),
                ('Children', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100, null=True)),
                ('Destination_Hotel', models.CharField(blank=True, choices=[('kathmandu', 'kathmandu'), ('bhaktapur', 'bhaktapur'), ('sanga', 'sanga'), ('banepa', 'banepa'), ('dhulikhel', 'dhulikhel'), ('panauti', 'panauti')], max_length=100, null=True)),
                ('Choose_Hotel', models.CharField(choices=[('Annapurna', 'Annapurna'), ('Kumar Hotel', 'Kumar Hotel'), ('Hotel A One', 'Hotel A One'), ('Family Resort', 'Family Resort'), ('Dhulikhel Valley Resort', 'Dhulikhel Valley Resort'), ('Dakshinkali Home Stay-OYO', 'Dakshinkali Home Stay-OYO'), ('Bhaktapur Valley View Resort', 'Bhaktapur Valley View Resort'), ('Panauti Hotel', 'Panauti Hotel'), ('KU Home Stay', 'KU Home Stay'), ('Devithan Valley Resort', 'Devithan Valley Resort'), ('Chandeswori Home Stay-OYO', 'Chandeswori Home Stay-OYO'), ('Kavre-Bhaktapur Valley Resort', 'Kavre-Bhaktapur Valley Resort'), ('Ra.Ts Valley Resort', 'Ra.Ts Valley Resort')], max_length=100)),
                ('Bed_type', models.CharField(blank=True, choices=[('Queen Size Bed', '7'), ('Deluxe Bed', '5'), ('Normal Bed', '4'), ('Double Bed', '4'), ('Single Bed', '3')], max_length=100, null=True)),
                ('Rate', models.FloatField(blank=True, max_length=50, null=True)),
                ('Description', models.TextField(blank=True, max_length=100, null=True)),
                ('Room_Type', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Roombooking.roomcategory')),
            ],
        ),
    ]
