# Generated by Django 4.0.4 on 2022-07-06 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.CharField(blank=True, choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedtype', models.CharField(blank=True, choices=[('abc', 'abc'), ('bcd', 'bcd'), ('efg', 'efg'), ('ghi', 'ghi'), ('jkl', 'jkl')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children', models.CharField(blank=True, choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChooseHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosehotel', models.CharField(blank=True, choices=[('abc', 'abc'), ('bcd', 'bcd'), ('efg', 'efg'), ('ghi', 'ghi'), ('jkl', 'jkl')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destinationhotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinationhotel', models.CharField(blank=True, choices=[('kathmandu', 'kathmandu'), ('bhaktapur', 'bhaktapur'), ('sanga', 'sanga'), ('banepa', 'banepa'), ('dhulikhel', 'dhulikhel'), ('panauti', 'panauti')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Category', models.CharField(max_length=50)),
                ('Rate', models.FloatField()),
                ('Description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.IntegerField()),
                ('District', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('Street', models.CharField(blank=True, max_length=100, null=True)),
                ('Emergency_Phone', models.IntegerField()),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Arrive_Date', models.DateField(blank=True, max_length=100, null=True)),
                ('Depart_Date', models.DateField(blank=True, max_length=100, null=True)),
                ('Rate', models.FloatField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=100, null=True)),
                ('Adult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Roombooking.adult')),
                ('Bed_Type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Roombooking.bedtype')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Roombooking.roomcategory')),
                ('Children', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Roombooking.children')),
                ('Choose_Hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Roombooking.choosehotel')),
                ('Destination_Hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Roombooking.destinationhotel')),
            ],
        ),
    ]
