# Generated by Django 4.0.4 on 2022-07-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roombooking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='Bed_Type',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='Category',
        ),
        migrations.AddField(
            model_name='roombooking',
            name='Bed_type',
            field=models.CharField(choices=[('abc', 'abc'), ('bcd', 'bcd'), ('efg', 'efg'), ('ghi', 'ghi'), ('jkl', 'jkl')], default=True, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roombooking',
            name='Room_Type',
            field=models.CharField(choices=[('with bathroom', 'with bathroom'), ('without bathroom', 'without bathroom'), ('deluxe room', 'deluxe room'), ('super deluxe room', 'super deluxe room'), ('normal room', 'normal room')], default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='Adult',
            field=models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five')], default=True, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='Children',
            field=models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five')], default=True, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='Choose_Hotel',
            field=models.CharField(choices=[('abc', 'abc'), ('bcd', 'bcd'), ('efg', 'efg'), ('ghi', 'ghi'), ('jkl', 'jkl')], default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='Destination_Hotel',
            field=models.CharField(choices=[('kathmandu', 'kathmandu'), ('bhaktapur', 'bhaktapur'), ('sanga', 'sanga'), ('banepa', 'banepa'), ('dhulikhel', 'dhulikhel'), ('panauti', 'panauti')], default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Adult',
        ),
        migrations.DeleteModel(
            name='BedType',
        ),
        migrations.DeleteModel(
            name='Children',
        ),
        migrations.DeleteModel(
            name='ChooseHotel',
        ),
        migrations.DeleteModel(
            name='Destinationhotel',
        ),
    ]
